routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('couriers', 'CourierController');
Route::get('list-couriers/{type}', 'CourierController@listCouriers')->name('couriers.list-couriers');
Route::post('forward-couriers/{id} ','CourierController@forwardCouriers')->name('couriers.forward-couriers');

app/Courier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Courier extends Model
{
  
  protected $fillable = [
    'from',
    'to', 
    'received_by', 
     'handovers',
    'type', 
    'posted_by'


    //'handovers' => 'array'
    ];
  }

app/CourierHandler.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CourierHandler extends Model
{
	 protected $table ='couriers_handlers';
    protected $fillable = [
    'courier_id',
    'user_id'
 
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CourierController.php
<?php
namespace App\Http\Controllers;
use App\Courier;
use App\User;
use App\DB;
use App\CourierHandler;
use Illuminate\Http\Request;
class CourierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

      return view('couriers.index');
    }
    public function listCouriers($type)
    {
      $couriers = Courier::where('type', $type)->get();
      if($type == 'inward')
      {

        return view('couriers.list-inward', compact('couriers'));
      }
      else if($type == 'outward')
      {
        return view('couriers.list-outward', compact('couriers'));
      }
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function store(Request $request)
    {
      $request->validate([
       'from'=>'required',
       'to'=>'required'
     ]);

      if ($request->type=='inward')
      {
        $couriers = Courier::create([
         'from'=>$request->from,
         'to'=>$request->to,
         'received_by'=>$request->received_by,
        //'handovers'=>$request->handovers,
         'type'=>'inward'
       ]);
      }
      else if($request->type=='outward')
      {
       $couriers = Courier::create([
         'to'=>$request->to,
         'from'=>$request->from,
         'posted_by'=>$request->posted_by,
         'type'=>'outward'
       ]);
     }
     echo "Successfully Added";
   }
    /**
     * Display the specified resource.
     *
     * @param  \App\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,  $id)
    {
      $courier = Courier::find($id); //for courier detail

      $users = User::all(); //for dropdown
      $handovers = CourierHandler::where('courier_id',$courier->id)->get();

      return view('couriers.show', compact('courier','users', 'handovers'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,  $id)
    {
     $couriers = Courier::find($id);

     return view('couriers.edit', compact('couriers'));
   }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,  $id)
    {
     $couriers= Courier::find($id);
     $couriers->from=$request->get('from');
     $couriers->to=$request->get('to');
     $couriers->received_by=$request->get('received_by');
     $couriers->posted_by=$request->get('posted_by');
     //$couriers->handovers=$request->get('handovers');
     $couriers->save();
     return redirect('/couriers')->with('status', 'updated Sucessfully');

   }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Courier  $courier
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $couriers = Courier::find($id)->delete();
      return redirect()->back()->with('success', 'deleted Successfully');
    }

    public function forwardCouriers(Request $request,  $id)
    {
     $couriers = CourierHandler::create([
      'user_id' => $request->user_id,
      'courier_id'=> $id,
    ]);

    echo "success";
   }

 }

resources/views/couriers/create.blade.php
@extends('layout1')

@section('title', 'Courier Management')

@section('content')

  <form action="{{ route('couriers.store') }}" method="post">
    @csrf
    <p class="center-align">COURIER  MANGEMENT</p>

     <div class="row">
      <div class="input-field col s6">
        <textarea name="from" class="materialize-textarea"></textarea>
        <label for="input_text">From</label>
      </div>
      <div class="input-field col s6">
       <textarea name="to" class="materialize-textarea"></textarea>
        <label for="textarea1">To</label>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s6">
        <textarea name="received_by" class="materialize-textarea"></textarea>
        <label for="textarea1">Received By</label>
      </div>
   
      <div class="input-field col s6">
        <textarea name="handover_to" class="materialize-textarea"></textarea>
        <label for="textarea1">Handover To</label>
      </div>
    <div class="row">
     <center><div class="input-field col s12">
        <button type="submit" class="btn waves-effect waves-light">Submit
        </button></center> 
      </div>
    </div> 
  </form></center>
@endsection

resources/views/couriers/create1.blade.php
@extends('layout1')

@section('title', 'Courier Management')

@section('content')

  <form action="{{ route('couriers.store') }}" method="post">
    @csrf
    <p class="center-align">COURIER  MANGEMENT</p>

     <div class="row">
      
      <div class="input-field col s6">
        <input name="to" type="text">
        <label for="textarea1">To</label>
      </div>
     <div class="input-field col s6">
        <input name="from" type="text" >
        <label for="input_text">From</label>
      </div>


    </div>
    <div class="row">
      <div class="input-field col s6">
        <textarea name="posted_by" class="materialize-textarea"></textarea>
        <label for="textarea1">Posted By</label>
      </div>
   
    <div class="row">
     <center><div class="input-field col s12">
        <button type="submit" class="btn waves-effect waves-light">Submit
        </button></center> 
      </div>
    </div> 
  </form>
@endsection

resources/views/couriers/edit.blade.php
@extends('layout1')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class=" uper">
 
  <div class="body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('couriers.update', $couriers->id) }}">
        @method('PATCH')
        @csrf

      <div class="row">
      
        <div class=" col sm-12">
          <div class="form-group">
           <label >From</label>
        <input name="from" type="text"   class="form-control"value={{ $couriers->from }} /> 
        </div></div></div>
        <div class="row">
        <div class="col sm-12">
           <div class="form-group">
           <label>To</label>
        <input name="to" type="text" class="form-control" value={{ $couriers->to }} /> 
       
      </div></div></div>
    

       <div class="row">
      <div class="col sm-12">
          <div class="form-group">
         <label >Received By</label>
        <input name="received_by" type="text"   class="form-control" value={{ $couriers->received_by }} /> 
       
      </div></div></div>
      <div class="row">
      <div class=" col sm-12">
         <div class="form-group">
        <label>Handovers</label>
        <input name="handovers" type="text"  class="form-control" value={{ $couriers->handovers}} /> 
        </div>
      </div>
    </div>

       <div class="row">
      <div class="col sm-12">
         <div class="form-group">
         <label>Posted By</label>
        <input name="posted_by" type="text"  class="form-control"  value={{ $couriers->posted_by }} /> 
       
      </div></div></div>
      <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/couriers/index.blade.php
@extends('layout1')
@section('content')

<div class="form-group">
	<div class="row">	
		<div class="col sm-12">
			<br><br><br>
		<center>	<a class="btn btn-lg btn-primary" href="{{ route('couriers.list-couriers', 'inward' )}}">Inward Couriers</a>
			<a  class="btn btn-lg btn-primary" href="{{ route('couriers.list-couriers', 'outward' )}}">Outward Couriers</a></center>
		</div></div></div>
		@endsection

resources/views/couriers/list-inward.blade.php
@extends('layout1')
@section('content')
<style>
.uper {
  margin-top: 40px;
}
</style>

@if(session()->get('success'))
<div class="alert alert-success">
  {{ session()->get('success') }}  
</div><br />
@endif
<div class="form-group">
  <div class="row">
    <div class="col sm-12">
     <h4><b>INWARD COURIERS</b></h4>
     <a href="{{ route('couriers.index') }}" class="btn btn-primary">Back</a>

     <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add New</button>
   </div></div></div>
   <table id="example" class="table table-striped table-bordered" style="width:100%">
    <thead>
      <tr>
        <th>ID</th>
        <th>Form</th>
        <th>To</th>
        <th>Received By</th>
        <th>Handovers</th>
        <th>Date</th>
        <th colspan="1">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach($couriers as $couriers)
      <tr>
        <td>{{$couriers->id}}</td>
        <td>{{$couriers->from}}</td>
        <td>{{$couriers->to}}</td>
        <td>{{$couriers->received_by}}</td>
        <td>{{$couriers->handovers}}</td>
        <td>{{$couriers->created_at}}</td>
        <!-- <td><a href="{{ route('couriers.edit', $couriers->id) }}">  <i class="small material-icons">edit</i></td>--> 
          <td>
           <a href="{{ route('couriers.show', $couriers->id) }}"><i class="glyphicon glyphicon-eye-open"></i></a>

           <a href="{{ route('couriers.edit', $couriers->id) }}"><i class="glyphicon glyphicon-pencil"></i></a>

           <a href="#" 
           onClick="event.preventDefault(); 
           if(confirm('Are you sure?')) {
           document.getElementById('inwardDelete-{{$couriers->id}}').submit();
         }
         ">
         <i class="glyphicon glyphicon-trash"></i>
       </a>
       <form id="inwardDelete-{{$couriers->id}}" action="{{ route('couriers.destroy', $couriers->id) }}" method="post">
        @csrf
        @method('delete')
      </form>
    </td>
  </tr>
  @endforeach
</tbody>
</tfoot>
</table>
<div class="container"> 
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">    
      <div class="modal-content">
        <div class="modal-header">
         <h4>Add New</h4>
       </div>
       <div class="modal-body">
         <div class="row">
          <div class="col sm-12">
            <label >From</label>
            <input  id="from1" type="text" class="form-control"  placeholder="form" />
          </div></div>
          <div class="row">
            <div class="col sm-12">
              <label>To</label>
              <input id="to1"  type="text" class="form-control" placeholder="To"> 
            </div></div>
            <div class="row">
              <div class="col sm-12">
                <label>Received By</label>
                <input id="received_by" type="text" class="form-control" placeholder="Received By" />
              </div>
            </div>
            
          </div>
          <div class="modal-footer">
            <button  id="submitInward"class="btn btn-primary" data-dismiss="modal">Submit</button>
            <!--<a href="#!"   id="submitInward" class="modal-close waves-effect waves-green btn-flat">Submit</a>-->
          </div>
        </div>

      </div>
    </div>
  </div>
  @endsection
  @push('scripts')
  <script>
    $(document).ready(function() {
   // $('.modal fade').modal();
   $('#submitInward').on('click', function(){
     var to = $('#to1').val();
     var from = $('#from1').val();
     var received_by = $('#received_by').val();

     $.post( "/couriers", {
      '_token': "{{ csrf_token() }}", 
      'to':to,
      'from':from,
      'received_by':received_by,   
      'type': 'inward'
    }, 
    function(data){
     console.log(data);
     location.reload();
     $('#to1').val('');
     $('#from1').val('');
     $('#received_by').val('');

   }); 
   });

   // $('#example').DataTable( {
//columnDefs: [
     // {
       // targets: [ 0, 1, 2 ],
       // className: 'mdl-data-table__cell--non-numeric'
      //}
     // ]
    //} );
  // } );
//$(document).ready(function() {
  $('#example').DataTable( {
   colReorder: true
 } );
} );
</script>
@endpush

resources/views/couriers/list-outward.blade.php
@extends('layout1')
@section('content')
<style>
.uper {
  margin-top: 40px;
}
</style>
@if(session()->get('success'))
<div class="alert alert-success">
  {{ session()->get('success') }}  
</div><br/>
@endif
<div class="form-group">
  <div class="row">
    <div class="col sm-12">  
     <h4><b>OUTWARD COURIERS</b></h4>
     <a href="{{ route('couriers.index') }}" class="btn btn-primary">Back</a>
     <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Add New</button>
   </div>
 </div></div>
 <table id="example" class="table table-striped table-bordered" style="width:100%">

 <thead> 

    <tr>
      <th>ID</th>
      <th>Form</th>
      <th>To</th>
      <th>Posted By</th>
      <th>Date</th>
      <th colspan="1">Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach($couriers as $couriers)
    <tr>
     <td>{{$couriers->id}}</td>
     <td>{{$couriers->from}}</td>
     <td>{{$couriers->to}}</td>   
     <td>{{$couriers->posted_by}}</td>
     <td>{{$couriers->created_at}}</td>
     <td>
      <a href="{{ route('couriers.show', $couriers->id)}}"><i class="glyphicon glyphicon-eye-open"></i></a>
      <a  href="{{ route('couriers.edit', $couriers->id) }}"><i class="glyphicon glyphicon-pencil"></i></a>
      <a href="" 
      onClick="event.preventDefault(); 
      if(confirm('Are you sure?')) {
      document.getElementById('outwardDelete-{{$couriers->id}}').submit();
    }
    ">
    <i class="glyphicon glyphicon-trash"></i>
  </a>
  <form id="outwardDelete-{{ $couriers->id }}" action="{{ route('couriers.destroy',$couriers->id) }}" method="post">
    @csrf
    @method('delete')
  </form>
</td>
</tr>
@endforeach
</tbody>
</table>

<div class="container"> 
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <div class="modal-content">
        <div class="modal-header">
         <h4>Add New</h4>
       </div>
       <div class="modal-body">
         <div class="row">
          <div class="col sm-12">

            <label >From</label>
            <input  id="from2" type="text" class="form-control"  placeholder="form" />
          </div></div>
          <div class="row">
            <div class="col sm-12">
              <label>To</label>
              <input id="to2"  type="text" class="form-control" placeholder="To"> 
            </div></div>
            <div class="row">
              <div class="col sm-12">
                <label>Posted By</label>
                <input id="posted_by" type="text" class="form-control" placeholder="Posted By" />
              </div>
            </div>

          </div>
          <div class="modal-footer">
            <button  id="submitOutward" class="btn btn-primary" data-dismiss="modal">Submit</button>
           
          </div>
        </div>

      </div>
    </div>

  </div>


@endsection
@push('scripts')
<script>
 $(document).ready(function() {
  //$('.modal').modal();
   $('#submitOutward').on('click', function(){
    var from = $('#from2').val();
    var to = $('#to2').val();
    var posted_by = $('#posted_by').val();
    $.post( "/couriers", {
      '_token': "{{ csrf_token() }}", 
      'to':to,
      'from':from,
      'posted_by':posted_by,
      'type': 'outward'
    }, 
    function(data){
      console.log(data);
      location.reload();
      $('#from2').val('');
      $('#to2').val('');
      $('#posted_by').val('');

    }); 
  });
   $('#example').DataTable( {
     colReorder: true
   } );
 } );
</script>
@endpush

resources/views/couriers/show.blade.php
@extends('layout1')
@section('content')
<style>
.uper {
	margin-top: 40px;
}
</style>
<div class=" uper">
	<div class="body">
		@if ($errors->any())
		<div class="alert alert-danger">
			<ul>
				@foreach ($errors->all() as $error)
				<li>{{ $error }}</li>
				@endforeach
			</ul>
		</div><br />
		@endif
		<a href="{{route('couriers.index')}}" class="btn btn-primary">Back</a>
		<div class="row">
			<div class="col-sm-8">
				<div class="form-group">
					<div class="col sm-2">
						<h6>Form:{{ $courier->from }}</h6>
					</div>
					<div class="col sm-2">
						<h6>To:{{ $courier->to }}</h6>
					</div>
					<div class="col sm-2">
						<h6>Received By:{{$courier->received_by }}</h6>
					</div>
				 <div class="col sm-2">
						<h6>Posted By:{{ $courier->posted_by }} </h6>
					</div>


					<label for="handover_users">Handovers To</label>
					<select class="form-control" class="handover_to" id="select2">
						@foreach ($users as $row)
						<option value="{{ $row->id }}">{{ $row->name }}</option>
						@endforeach
					</select><br>
					<button id="submitInwardforward" class="btn btn-primary">Forward By</button>
				</div>
			</div>
			<input type="hidden" id="courier_id" value="{{ $courier->id }}">
			<div class="col-lg-4">
				<div class="form-group">
					<h5>Comments</h5>
					<textarea class="form-control" id="comments" rows="3"></textarea>
				</div>
			<center><button type="button" class="btn btn-primary">Submit</button>	</center>
			</div>
				</div>
			</div>
		</div>
		<div class="row">
		<div class="col-sm-8">
   <div class="form-group">
				<h5><b>Handovers</b></h5>

					 <table id="example"  class="table table-striped table-bordered" style="width:100%">

						<thead>
							<tr>
								<th>Name</th>
								<th>Date of Handover</th>
							</tr>
						</thead>
						<tbody>
							@foreach($handovers as $handover)
							<tr>
								<td>{{ \App\User::where('id', $handover->user_id)->pluck('name')->first() }}</td>
								<td>{{ $handover->created_at }}</td>
							</tr>
							@endforeach
						</tbody>
					</table>
				</div>
			</div>

		</div>
		@endsection

			@push('scripts')
				<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
				<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
			<script>
				$(document).ready(function() {
					$('#select2').select2();

					$('#submitInwardforward').on('click', function(){
						var user_id =  $('#select2').val();
						var courier_id= $('#courier_id').val();

						$.post( "/forward-couriers/"+courier_id, {'_token': "{{ csrf_token() }}", 'user_id':user_id }, function(data){
							alert(data);
						});
					});
				});

</script>
@endpush

resources/views/layout1.blade.php
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/colreorder/1.5.1/css/colReorder.bootstrap.min.css">
  <title>Courier management</title>


  @stack('styles')
</head>
<body>
  <div class="container">
    @yield('content')
  </div>
  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" ></script>

  @stack('scripts')
</body>
</html>

resources/views/layout2.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Courier management</title>
     <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
  </head>
 <body>
    <div class="container">
      @yield('content')
    </div>
   
</body>
</html>